"""update models

Revision ID: 3c085e639df7
Revises: 66530c5b499f
Create Date: 2025-10-21 14:01:07.816088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c085e639df7'
down_revision: Union[str, Sequence[str], None] = '66530c5b499f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_vin'), table_name='car')
    op.drop_index(op.f('ix_claim_car_id_claim_date'), table_name='claim')
    op.drop_index(op.f('ix_insurance_policy_car_id_start_date_end_date'), table_name='insurance_policy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_insurance_policy_car_id_start_date_end_date'), 'insurance_policy', ['car_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_claim_car_id_claim_date'), 'claim', ['car_id', 'claim_date'], unique=False)
    op.create_index(op.f('ix_car_vin'), 'car', ['vin'], unique=1)
    # ### end Alembic commands ###
