from typing import Protocol, TypeVar, Generic, Iterable, Optional

T = TypeVar("T")
ID = TypeVar("ID", int, str)

class BaseRepository(Protocol, Generic[T, ID]):
    def get(self, id: ID) -> Optional[T]: ...
    def add(self, entity: T) -> T: ...
    def list(self) -> Iterable[T]: ...
    def delete(self, id: ID) -> None: ...
    def update(self, entity: T) -> T: ...