services:
  db:
    image: postgres:16
    container_name: car-insurance-postgres
    env_file:
      - ../.env.production
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 3s
      retries: 20

  migrate:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: car-insurance-migrate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../.env.production
    working_dir: /app
    command: alembic -c /app/alembic.ini upgrade head

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: car-insurance-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file:
      - ../.env.production
    volumes:
      - ../app:/app/app
      - ../alembic:/app/alembic
      - ../alembic.ini:/app/alembic.ini
    working_dir: /app
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
    ports:
      - "${PORT:-8000}:8000"

volumes:
  pgdata:
