services:
  policy-check-job:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: car-insurance-policy-check-job-dev
    env_file:
      - ../.env.development
    working_dir: /app
    depends_on:
      app: 
        condition: service_healthy
    command: python jobs/policy_check.py
    volumes:
      - ../logs/dev:/app/logs/dev
      - sqlite-data:/app/data/sqlite
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: car-insurance-app-dev
    env_file:
      - ../.env.development
    volumes:
      - ../app:/app/app
      - sqlite-data:/app/data/sqlite
      - ../alembic:/app/alembic
      - ../alembic.ini:/app/alembic.ini
        - ../logs/dev:/app/logs/dev
    command: >
      sh -c "
        alembic -c /app/alembic.ini upgrade head &&
        python scripts/create_superadmin.py &&
        uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}
      "
    ports:
      - "${PORT:-8005}:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      
volumes: 
  sqlite-data: