services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: car-insurance-app-dev
    env_file:
      - ../.env.development
    volumes:
      - ../app:/app/app
      - sqlite-data:/app/data/sqlite
      - ../alembic:/app/alembic
      - ../alembic.ini:/app/alembic.ini

    command: >
      sh -c "alembic -c /app/alembic.ini upgrade head
      && uvicorn app.main:app --reload --host 0.0.0.0 --port ${PORT:-8000}"
    ports:
      - "${PORT:-8005}:8000"
    restart: always

volumes: 
  sqlite-data: